Version 0.1
Dhii/di-abstract pull request #1
Opened 2017-01-31 13:43 UTC by mecha

Initial release, containing the abstract implementations.

## Added
- Abstract implementations;
- Functional tests.

2017-01-31 13:44 UTC, mecha commented
Once https://github.com/Dhii/di-interface/pull/1 is merged, this package can depend on `dhii/di : ^0.1`.

2017-02-01 13:58 UTC, XedinUnknown requested changes
[This](https://github.com/Dhii/di-abstract/blob/release/0.1/src/AbstractCompositeContainer.php#L91) will not work with `Traversable`. Try [`iterator_to_array()`](http://php.net/manual/en/function.iterator-to-array.php)

2017-02-01 14:24 UTC, mecha commented
@XedinUnknown Why won't it work with `Traversable`? The array pointer PHP functions are all compatible with `Iterator` implementations, and according to the PHP manual the `Iterator` interface is what makes objects `Traversable`.

> Abstract base interface that cannot be implemented alone. Instead it must be implemented by either IteratorAggregate or Iterator.

2017-02-01 14:30 UTC, XedinUnknown commented
@mecha, where does it say that PHP array pointer functions are compatible with `Traversable`? IMHO, this is not possible by design, at least because `Iterator` is not the only `Traversable` interface.

To make things simpler, modify the test to use a `Traversable` instead of an array, and if it passes, I will approve.

2017-02-01 14:36 UTC, mecha commented
@XedinUnknown I happen to know from experience that it works. I've also just tested it across all PHP versions using [this tool](https://3v4l.org/) using the code:

```php
function foobar(Traversable $t) {
    return end($t);
}
echo foobar(new ArrayIterator(array(1, 21, 42)));
```

I couldn't find any documentation that listed what classes (specifically built-in classes) implement `Traversable`. In fact I think nothing implements this, save for `array()` internally.

Still, if you prefer this done differently I will comply.

2017-02-01 14:49 UTC, XedinUnknown commented
@mecha, please try [this](https://3v4l.org/fpoIK). Function `barfoo()` should explain why there's no error.

2017-02-01 17:13 UTC, mecha commented
@XedinUnknown Updated PR.

Introduced [`AbstractCompositeContainer#_getContainersReversed()`][1]. This can be overridden by implementations if an iterator is needed.

[`AbstractCompositeContainer#_hasDelegated()`][2] now relies on that method and iterates on whatever that method returns.

[1]: https://github.com/Dhii/di-abstract/blob/release/0.1/src/AbstractCompositeContainer.php#L130
[2]: https://github.com/Dhii/di-abstract/blob/release/0.1/src/AbstractCompositeContainer.php#L90

2017-02-02 07:45 UTC, XedinUnknown approved these changes

2017-02-02 13:38 UTC, XedinUnknown commented
@mecha, last look before release please.

2017-02-02 13:42 UTC, mecha commented on src/AbstractCompositeContainer.php
>       * @todo To check if the $container instance should play a part in ID generation.
@XedinUnknown Remove this tag?

2017-02-02 13:45 UTC, mecha commented
@XedinUnknown There is also [this `todo` tag](https://github.com/Dhii/di-abstract/blob/master/src/AbstractContainer.php#L62). Worth discussing as I can't see any scenario where the method can return `null`.

2017-02-02 14:19 UTC, XedinUnknown commented
@mecha, check now please.

2017-02-02 14:28 UTC, mecha commented on src/AbstractCompositeContainer.php
>          return ($having)
This check is now obsolete. I would also recommend inverting the `if` condition for cleaner code.

```php
if ($having = $this->_getDelegated($id)) {
    return $having->get($id)
}

throw $this->_createNotFoundException(sprintf('Could not create service for ID "%1$s": no service defined', $id));
```

2017-02-02 14:35 UTC, XedinUnknown commented on src/AbstractCompositeContainer.php
>          return ($having)
Fixed check. I think I prefer to throw in the condition, though.

2017-02-02 14:38 UTC, mecha commented on src/AbstractCompositeContainer.php
>          return ($having)
Up to you. Both look good to me now after the ternary check fix.

2017-02-02 18:30 UTC, merged